meta_product_name: "DocPat"
meta_title: "DocPat - Your health, always."
meta_description: "Join DocPat and be in control of your family’s health history and documentation"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards


